### ISSUE TITLE
Can't find list ID

### ISSUE THREAD

**Issue by Yswag** [jonjonsson/Emby-MDBList-Collection-Creator#1]
Hello, I tried to create [this list](https://mdblist.com/lists/lpukatch/tspdt) but couldn't find list ID in source like the examples, is there a solution? Thank you.

**Comment by jonjonsson** [comment]
Hey. This is a static list and I haven't been able to figure out how to get the list ID. 

The work around is that the script can grab all the lists you have in My Lists https://mdblist.com/mylists/ 
So you can just open the list on MDBList and go to Actions and select Create Static List, then it's part of your lists and the script will automatically grab it.

![image](https://github.com/jonjonsson/Emby-MDBList-Collection-Creator/assets/2595929/e5151897-d17f-4160-8980-1e23b9271db5)

**Comment by jonjonsson** [comment]
Hey, I added a new method to add lists that doesn't require list ID. Instead of using list ID you specify the MDBList name and user name in the config.

# Example
[TSPDT 1000]
List_Name = TSPDT 1000
User_Name = lpukatch
Source = https://mdblist.com/lists/lpukatch/tspdt
Frequency = 100
