### ISSUE TITLE
Enhancement Request: Additional Collection Sorting Options

### ISSUE THREAD

**Issue by coding-blip** [jonjonsson/Emby-MDBList-Collection-Creator#10]
First off, thanks for this project as it finally allowed me to set up automatic seasonal collections!

According to the readme and config file examples, it looks like currently it is supported to sort a created collection by date added to Emby. It would be cool if you could add a sorting option to sort a generated collection alphabetically. This would be nice as my main use case for this is seasonal collections, so I just want an easy way to see my seasonal content in a "short" list and having it be alphabetical would be a nice benefit!

**Comment by jonjonsson** [comment]
Ah ok,

make sure this is set to False
`update_items_sort_names_default_value = False`

And for each collection this should be set to False
`update_items_sort_names = False`

By default the items will sort by alphabetical order inside collections so if you turn these 2 off you should be good. If that is not the case it's possible the sort order has been changed in Emby Client, then set it back to Collection Order.
![image](https://github.com/user-attachments/assets/077859f5-9e0d-4b0f-ae23-bcc431cbc058)

**Comment by coding-blip** [comment]
Oh wow, this is my first time using collections and I am new to Emby, but I never noticed that sorting option in Emby before. Thanks for pointing it out, that's really handy!

I'll close this now as nothing actually needs to be done. Thanks @jonjonsson!
