### ISSUE TITLE
Question: Can the script be modified to backup selected users only?

### ISSUE THREAD

**Issue by amokster88** [jonjonsson/Emby-MDBList-Collection-Creator#15]
Hi,

Thank you for the great work on this project! I have a question regarding the backup functionality in `app_backup.py` & `app_restore_backup.py`.

Is it possible to modify the script so that it only backs/restores selected users rather than all users? If this feature is not currently supported, could you please implement it?

Any help would be greatly appreciated!

Best regards.

**Comment by jonjonsson** [comment]
Hey @amokster88. You can run the backup job and that creates a json file for all the users. Then you can just restore for the user you like with:

python3 restore_backup.py -host http://xxx.xxx.xxx.xxx:xxxx -user_id abc123 -api_key abc123 -source_file "backup\IsPlayed_SomeUsername.json"

Where the user_id is the name on emby you want to restore to and source_file is the json for that user.

**Comment by jonjonsson** [comment]
Ah I get you, I updated the script. Can add 

backup_user_names = john,yoko

to your config now.
