### ISSUE TITLE
Enhancement Request: Collection scheduling

### ISSUE THREAD

**Issue by cj0r** [jonjonsson/Emby-MDBList-Collection-Creator#4]
Not an issue but a feature request/enhancement to your script. I was wondering if it could be enhanced to add/remove collections depending on time ranges? For instance having a Collection generated for Halloween or Christmas films that comes and goes with the season.

Stumbled upon this while looking for a kometa substitute (can get most of the way between this script and posterizarr) and really love that it works exactly as advertised and the simplicity/tie in with mdblist is perfect. Keep up the good work!

**Comment by jonjonsson** [comment]
Hey, I really like that idea! I hit a wall though. I asked for help here: https://emby.media/community/index.php?/topic/132965-delete-collection-with-api-not-working/

Will update the script as soon as I figure that out.

**Comment by jonjonsson** [comment]
@cj0r Feature is added now, thanks for the idea!
