### ISSUE TITLE
some error

### ISSUE THREAD

**Issue by mcfalld** [jonjonsson/Emby-MDBList-Collection-Creator#5]
refresher.process_collection(
  File "C:\Users\Derrick\Downloads\Emby-MDBList-Collection-Creator-main\Emby-MDBList-Collection-Creator-main\refresher.py", line 54, in process_collection
    created_date = datetime.fromisoformat(
ValueError: Invalid isoformat string: '2020-05-02T18:21:45.0000000+00:00'

**Comment by jonjonsson** [comment]
Hey, I can't reproduce this, works on my end with that string:

`from datetime import datetime

created_date = datetime.fromisoformat(
    "2020-05-02T18:21:45.0000000+00:00".replace("Z", "+00:00")
)

print(created_date)
`

I don't know why you are getting this error.  I updated the script to catch it and continue on at least. You can try it out.

What Python version are you using?

**Comment by PizzaPino** [comment]
I'm getting this error:

```
SUMMARY: Added 4513 to collections and removed 0

Setting sort names for new items in collections
Updated item 579560 with {'DisplayOrder': 'SortName'}. Waiting 1 seconds.
Traceback (most recent call last):
  File "/home/tmoliver/Emby-MDBList-Collection-Creator/app.py", line 365, in <module>
    main()
  File "/home/tmoliver/Emby-MDBList-Collection-Creator/app.py", line 335, in main
    item_sorting.process_collection(collection_id)
  File "/home/tmoliver/Emby-MDBList-Collection-Creator/src/item_sorting.py", line 68, in process_collection
    new_sort_name = f"{self.sort_name_start}{self.minutes_until_2100(item['DateCreated'])}{self.sort_name_end}{item['SortName']}"
  File "/home/tmoliver/Emby-MDBList-Collection-Creator/src/item_sorting.py", line 31, in minutes_until_2100
    date = datetime.fromisoformat(iso_date.replace("Z", "+00:00"))
ValueError: Invalid isoformat string: '2024-04-15T14:08:04.0000000+00:00'
```

**Comment by jonjonsson** [comment]
Hey @PizzaPino, can you help me debug this please?

It's failing for you when trying to do this:

`
from datetime import datetime

date = datetime.fromisoformat(
    "2024-04-15T14:08:04.0000000+00:00".replace("Z", "+00:00")
)
print(date)

# result 2024-04-15 14:08:04+00:00
`

I can run this code fine. Can you see if you can run this snippet?

**Comment by PizzaPino** [comment]
this is what I get 

```
Traceback (most recent call last):
  File "/home/tmoliver/emby-mdblist2/app2.py", line 3, in <module>
    date = datetime.fromisoformat(
ValueError: Invalid isoformat string: '2024-04-15T14:08:04.0000000+00:00'
```

**Comment by jonjonsson** [comment]
OK, it's probably due to you having an older Python version. What do you have?

I will see if I can make more compatible, probably during the weekend.... or you can just update python assuming you have something lower than 3.11.

**Comment by PizzaPino** [comment]
yes, using python 3.11 made it all work without issues
